language: node_js
node_js: 8
sudo: true
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run codecov
env:
  global:
  - BX_APP=food-coach
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos

before_deploy: npm install -g bx-blue-green
deploy:
- provider: script
  skip_cleanup: true
  script:
  - bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/food-coach
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 8
