language: node_js
sudo: true
cache:
  directories:
  - node_modules
node_js: stable
script:
- npm run lint
- npm run codecov
env:
  global:
  - CF_APP=food-coach
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=WatsonPlatformServices
  - CF_SPACE=appgallery

before_deploy: npm install -g cf-blue-green
deploy:
  skip_cleanup: true
  provider: script
  script:
  - cf-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/food-coach
notifications:
  email: false
